DROPBOX_TOKEN = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
DROPBOX_APP_KEY = "XXXXXXXXXXXXXXX"
DROPBOX_APP_SECRET = "XXXXXXXXXXXXXXX"
DROPBOX_PATH = "/Users/sample/Dropbox"

BACKUP_PATH = "/backup"
APP_NAME = "your-app-name"
